-- 028_missing_master_tables.sql
-- total에 있고 hub엔 없던 수동입력/마스터 테이블 7종 이식 (biz_id 멀티테넌트).
-- 스키마는 total REST 샘플 기준. RLS는 daily_revenue 패턴(service_role_all + tenant_isolation).
-- 데이터는 별도 스크립트로 total→hub REST 이관(biz_id=1 태깅, total id 보존).
--
-- 대상: tax_invoices, expenses, bank_transactions, product_costs,
--       master_prices, master_bom, channel_costs

-- ─────────────── tax_invoices (세금계산서) ───────────────
CREATE TABLE IF NOT EXISTS tax_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id BIGINT NOT NULL,
    direction TEXT, invoice_number TEXT, mgt_key TEXT,
    write_date DATE, issue_date DATE,
    tax_type TEXT, charge_direction TEXT, issue_type TEXT, purpose_type TEXT,
    supplier_corp_num TEXT, supplier_corp_name TEXT, supplier_ceo_name TEXT,
    supplier_addr TEXT, supplier_biz_type TEXT, supplier_biz_class TEXT, supplier_email TEXT,
    buyer_corp_num TEXT, buyer_corp_name TEXT, buyer_ceo_name TEXT,
    buyer_addr TEXT, buyer_biz_type TEXT, buyer_biz_class TEXT, buyer_email TEXT,
    supply_cost_total NUMERIC DEFAULT 0, tax_total NUMERIC DEFAULT 0, total_amount NUMERIC DEFAULT 0,
    items JSONB, status TEXT, popbill_nts_result TEXT,
    matched_transaction_id BIGINT, partner_id BIGINT, memo TEXT, registered_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE, deleted_by TEXT,
    matched_amount NUMERIC DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_tax_invoices_biz ON tax_invoices (biz_id, write_date);

-- ─────────────── expenses (판관비/지출) ───────────────
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id BIGINT NOT NULL,
    expense_date DATE, expense_month TEXT, category TEXT, subcategory TEXT,
    amount NUMERIC DEFAULT 0, is_recurring BOOLEAN DEFAULT FALSE,
    tax_invoice_id BIGINT, memo TEXT, registered_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE, deleted_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_expenses_biz ON expenses (biz_id, expense_month);

-- ─────────────── bank_transactions (입출금) ───────────────
CREATE TABLE IF NOT EXISTS bank_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id BIGINT NOT NULL,
    bank_account_id BIGINT, transaction_date DATE, transaction_time TEXT,
    transaction_type TEXT, amount NUMERIC DEFAULT 0, balance NUMERIC DEFAULT 0,
    counterpart_name TEXT, counterpart_account TEXT, description TEXT, category TEXT,
    matched_invoice_id BIGINT, matched_settlement_id BIGINT, codef_transaction_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE, deleted_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_bank_tx_biz ON bank_transactions (biz_id, transaction_date);

-- ─────────────── product_costs (원가 마스터) ───────────────
CREATE TABLE IF NOT EXISTS product_costs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id BIGINT NOT NULL,
    product_name TEXT, cost_price NUMERIC DEFAULT 0, unit TEXT, memo TEXT,
    weight NUMERIC DEFAULT 0, weight_unit TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    cost_type TEXT, material_type TEXT, purchase_unit TEXT, standard_unit TEXT,
    conversion_ratio NUMERIC DEFAULT 1, safety_stock NUMERIC DEFAULT 0, lead_time_days INTEGER DEFAULT 0,
    is_production_target BOOLEAN, sales_category TEXT, food_type TEXT,
    is_stock_managed BOOLEAN DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE, deleted_by TEXT,
    category TEXT, storage_method TEXT
);
CREATE INDEX IF NOT EXISTS idx_product_costs_biz ON product_costs (biz_id, product_name);

-- ─────────────── master_prices (가격 마스터, 한글컬럼) ───────────────
CREATE TABLE IF NOT EXISTS master_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id BIGINT NOT NULL,
    "품목명" TEXT, "SKU" TEXT,
    "네이버판매가" NUMERIC DEFAULT 0, "쿠팡판매가" NUMERIC DEFAULT 0, "로켓판매가" NUMERIC DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_master_prices_biz ON master_prices (biz_id);

-- ─────────────── master_bom (세트 BOM, 한글컬럼) ───────────────
CREATE TABLE IF NOT EXISTS master_bom (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id BIGINT NOT NULL,
    "세트명" TEXT, "구성품" TEXT
);
CREATE INDEX IF NOT EXISTS idx_master_bom_biz ON master_bom (biz_id);

-- ─────────────── channel_costs (채널 비용 마스터) ───────────────
CREATE TABLE IF NOT EXISTS channel_costs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id BIGINT NOT NULL,
    channel TEXT, fee_rate NUMERIC DEFAULT 0, shipping NUMERIC DEFAULT 0,
    packaging NUMERIC DEFAULT 0, other_cost NUMERIC DEFAULT 0, memo TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE, deleted_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_channel_costs_biz ON channel_costs (biz_id);

-- ─────────────── RLS (전 테이블 동일 패턴) ───────────────
DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['tax_invoices','expenses','bank_transactions',
                             'product_costs','master_prices','master_bom','channel_costs']
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('DROP POLICY IF EXISTS service_role_all ON %I', t);
        EXECUTE format('CREATE POLICY service_role_all ON %I FOR ALL TO service_role USING (true) WITH CHECK (true)', t);
        EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', t);
        EXECUTE format($f$CREATE POLICY tenant_isolation ON %I FOR ALL TO authenticated
            USING (biz_id = (NULLIF(current_setting('app.current_biz_id', true), ''))::bigint)
            WITH CHECK (biz_id = (NULLIF(current_setting('app.current_biz_id', true), ''))::bigint)$f$, t);
    END LOOP;
END $$;
