-- 029_bank_expense_dependents.sql
-- 028의 의존 테이블 3종 이식 (입출금/판관비 메뉴 완결).
-- bank_accounts: bank_transactions가 참조(조인). expense_categories: 지출 분류.
-- codef_connections: 은행 스크래핑 연결(배마마 자기 데이터).
-- biz_id 멀티테넌트 + RLS(daily_revenue 패턴).

CREATE TABLE IF NOT EXISTS bank_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id BIGINT NOT NULL,
    connected_id TEXT, bank_code TEXT, bank_name TEXT,
    account_number TEXT, account_holder TEXT, account_type TEXT,
    is_active BOOLEAN DEFAULT TRUE, last_synced_at TIMESTAMPTZ, last_synced_date DATE,
    memo TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    client_type TEXT, is_deleted BOOLEAN NOT NULL DEFAULT FALSE, deleted_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_bank_accounts_biz ON bank_accounts (biz_id);

CREATE TABLE IF NOT EXISTS expense_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id BIGINT NOT NULL,
    name TEXT, parent TEXT, sort_order INTEGER DEFAULT 0, is_active BOOLEAN DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS idx_expense_categories_biz ON expense_categories (biz_id);

CREATE TABLE IF NOT EXISTS codef_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id BIGINT NOT NULL,
    connected_id TEXT, organization TEXT, login_type TEXT, status TEXT, memo TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_codef_connections_biz ON codef_connections (biz_id);

-- RLS
DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['bank_accounts','expense_categories','codef_connections']
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('DROP POLICY IF EXISTS service_role_all ON %I', t);
        EXECUTE format('CREATE POLICY service_role_all ON %I FOR ALL TO service_role USING (true) WITH CHECK (true)', t);
        EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', t);
        EXECUTE format($f$CREATE POLICY tenant_isolation ON %I FOR ALL TO authenticated
            USING (biz_id = (NULLIF(current_setting('app.current_biz_id', true), ''))::bigint)
            WITH CHECK (biz_id = (NULLIF(current_setting('app.current_biz_id', true), ''))::bigint)$f$, t);
    END LOOP;
END $$;
