-- 031_master_products.sql
-- 상품마스터(master) 메뉴용 master_products 테이블 생성.
-- total엔 없음(엑셀 업로드로 채우는 테이블). 빈 테이블 + biz_id + RLS만 생성해
-- 메뉴 동작(현황 count) 가능케 함. 컬럼은 product_costs 유사(업로드 호환).

CREATE TABLE IF NOT EXISTS master_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id BIGINT NOT NULL,
    product_name TEXT, barcode TEXT, category TEXT, unit TEXT,
    food_type TEXT, sales_category TEXT, storage_method TEXT,
    material_type TEXT, memo TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE, deleted_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_master_products_biz ON master_products (biz_id, product_name);

ALTER TABLE master_products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON master_products;
CREATE POLICY service_role_all ON master_products FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS tenant_isolation ON master_products;
CREATE POLICY tenant_isolation ON master_products FOR ALL TO authenticated
    USING (biz_id = (NULLIF(current_setting('app.current_biz_id', true), ''))::bigint)
    WITH CHECK (biz_id = (NULLIF(current_setting('app.current_biz_id', true), ''))::bigint);
