-- 034_missing_subsystem_tables.sql
-- hub 코드가 참조하나 미존재였던 24개 테이블 (인사/급여·회계/분개장·생산계획·상품·프로모션·정산).
-- total→hub 이관(17개 데이터 有, ~2819행) + 6개 빈테이블. 라이브 스키마에서 생성. biz_id+RLS.
-- ※ 데이터는 별도 REST 이관스크립트로 biz_id=1 태깅 적재됨.

CREATE TABLE IF NOT EXISTS account_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" TEXT,
  "name" TEXT,
  "category" TEXT,
  "parent_code" TEXT,
  "is_active" BOOLEAN,
  "sort_order" NUMERIC,
  "created_at" TIMESTAMPTZ,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_account_codes_biz ON account_codes(biz_id);
ALTER TABLE account_codes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON account_codes;
CREATE POLICY service_role_all ON account_codes FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON account_codes;
CREATE POLICY tenant_isolation ON account_codes FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS annual_leave (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" BIGINT,
  "leave_year" NUMERIC,
  "granted_days" NUMERIC,
  "used_days" NUMERIC,
  "memo" TEXT,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_annual_leave_biz ON annual_leave(biz_id);
ALTER TABLE annual_leave ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON annual_leave;
CREATE POLICY service_role_all ON annual_leave FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON annual_leave;
CREATE POLICY tenant_isolation ON annual_leave FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS card_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bank_account_id" BIGINT,
  "approval_date" TEXT,
  "approval_time" TEXT,
  "approval_no" TEXT,
  "merchant_name" TEXT,
  "amount" NUMERIC,
  "card_type" TEXT,
  "installment" TEXT,
  "is_cancelled" BOOLEAN,
  "category" TEXT,
  "description" TEXT,
  "matched_journal_id" BIGINT,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  "is_deleted" BOOLEAN,
  "deleted_by" TEXT,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_card_transactions_biz ON card_transactions(biz_id);
ALTER TABLE card_transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON card_transactions;
CREATE POLICY service_role_all ON card_transactions FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON card_transactions;
CREATE POLICY tenant_isolation ON card_transactions FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT,
  "position" TEXT,
  "department" TEXT,
  "base_salary" NUMERIC,
  "hire_date" TEXT,
  "status" TEXT,
  "memo" TEXT,
  "created_at" TIMESTAMPTZ,
  "resident_number_back" TEXT,
  "bank_name" TEXT,
  "bank_account" TEXT,
  "dependents_count" NUMERIC,
  "is_tax_exempt" BOOLEAN,
  "is_deleted" BOOLEAN,
  "deleted_by" TEXT,
  "retire_date" TEXT,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_employees_biz ON employees(biz_id);
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON employees;
CREATE POLICY service_role_all ON employees FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON employees;
CREATE POLICY tenant_isolation ON employees FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS event_account_mapping (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_type" TEXT,
  "debit_account" TEXT,
  "credit_account" TEXT,
  "description_template" TEXT,
  "is_active" BOOLEAN,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_event_account_mapping_biz ON event_account_mapping(biz_id);
ALTER TABLE event_account_mapping ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON event_account_mapping;
CREATE POLICY service_role_all ON event_account_mapping FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON event_account_mapping;
CREATE POLICY tenant_isolation ON event_account_mapping FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS insurance_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "year" NUMERIC,
  "insurance_type" TEXT,
  "employee_rate" NUMERIC,
  "employer_rate" NUMERIC,
  "min_base" NUMERIC,
  "max_base" NUMERIC,
  "notes" TEXT,
  "created_at" TIMESTAMPTZ,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_insurance_rates_biz ON insurance_rates(biz_id);
ALTER TABLE insurance_rates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON insurance_rates;
CREATE POLICY service_role_all ON insurance_rates FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON insurance_rates;
CREATE POLICY tenant_isolation ON insurance_rates FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS journal_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "journal_date" TEXT,
  "journal_type" TEXT,
  "description" TEXT,
  "total_debit" NUMERIC,
  "total_credit" NUMERIC,
  "status" TEXT,
  "ref_type" TEXT,
  "ref_id" BIGINT,
  "reversed_by" TEXT,
  "created_by" TEXT,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_journal_entries_biz ON journal_entries(biz_id);
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON journal_entries;
CREATE POLICY service_role_all ON journal_entries FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON journal_entries;
CREATE POLICY tenant_isolation ON journal_entries FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS journal_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "journal_entry_id" BIGINT,
  "line_no" NUMERIC,
  "account_code" TEXT,
  "account_name" TEXT,
  "debit_amount" NUMERIC,
  "credit_amount" NUMERIC,
  "description" TEXT,
  "created_at" TIMESTAMPTZ,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_journal_lines_biz ON journal_lines(biz_id);
ALTER TABLE journal_lines ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON journal_lines;
CREATE POLICY service_role_all ON journal_lines FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON journal_lines;
CREATE POLICY tenant_isolation ON journal_lines FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS leave_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" BIGINT,
  "leave_date" TEXT,
  "days" NUMERIC,
  "leave_type" TEXT,
  "memo" TEXT,
  "created_at" TIMESTAMPTZ,
  "deduction_amount" NUMERIC,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_leave_records_biz ON leave_records(biz_id);
ALTER TABLE leave_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON leave_records;
CREATE POLICY service_role_all ON leave_records FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON leave_records;
CREATE POLICY tenant_isolation ON leave_records FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS nontaxable_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "year" NUMERIC,
  "limit_type" TEXT,
  "monthly_limit" NUMERIC,
  "notes" TEXT,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_nontaxable_limits_biz ON nontaxable_limits(biz_id);
ALTER TABLE nontaxable_limits ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON nontaxable_limits;
CREATE POLICY service_role_all ON nontaxable_limits FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON nontaxable_limits;
CREATE POLICY tenant_isolation ON nontaxable_limits FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS payment_matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tax_invoice_id" BIGINT,
  "bank_transaction_id" BIGINT,
  "settlement_id" BIGINT,
  "match_type" TEXT,
  "match_status" TEXT,
  "matched_amount" NUMERIC,
  "invoice_amount" NUMERIC,
  "transaction_amount" NUMERIC,
  "difference" NUMERIC,
  "partner_name" TEXT,
  "memo" TEXT,
  "matched_by" TEXT,
  "matched_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ,
  "is_deleted" BOOLEAN,
  "deleted_by" TEXT,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_payment_matches_biz ON payment_matches(biz_id);
ALTER TABLE payment_matches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON payment_matches;
CREATE POLICY service_role_all ON payment_matches FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON payment_matches;
CREATE POLICY tenant_isolation ON payment_matches FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS payroll_monthly (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" BIGINT,
  "pay_month" TEXT,
  "base_salary" NUMERIC,
  "allowances" NUMERIC,
  "total_cost" NUMERIC,
  "memo" TEXT,
  "created_at" TIMESTAMPTZ,
  "position_allowance" NUMERIC,
  "responsibility_allowance" NUMERIC,
  "longevity_allowance" NUMERIC,
  "meal_allowance" NUMERIC,
  "vehicle_allowance" NUMERIC,
  "overtime_pay" NUMERIC,
  "night_pay" NUMERIC,
  "holiday_pay" NUMERIC,
  "bonus" NUMERIC,
  "other_allowance" NUMERIC,
  "other_allowance_detail" JSONB,
  "gross_salary" NUMERIC,
  "taxable_amount" NUMERIC,
  "nontaxable_amount" NUMERIC,
  "national_pension" NUMERIC,
  "health_insurance" NUMERIC,
  "long_term_care" NUMERIC,
  "employment_insurance" NUMERIC,
  "income_tax" NUMERIC,
  "local_income_tax" NUMERIC,
  "total_deductions" NUMERIC,
  "net_salary" NUMERIC,
  "national_pension_employer" NUMERIC,
  "health_insurance_employer" NUMERIC,
  "long_term_care_employer" NUMERIC,
  "employment_insurance_employer" NUMERIC,
  "industrial_accident_insurance" NUMERIC,
  "total_employer_cost" NUMERIC,
  "status" TEXT,
  "updated_at" TIMESTAMPTZ,
  "attendance_deduction" NUMERIC,
  "attendance_detail" JSONB,
  "proration_ratio" NUMERIC,
  "proration_days" NUMERIC,
  "calendar_days" NUMERIC,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_payroll_monthly_biz ON payroll_monthly(biz_id);
ALTER TABLE payroll_monthly ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON payroll_monthly;
CREATE POLICY service_role_all ON payroll_monthly FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON payroll_monthly;
CREATE POLICY tenant_isolation ON payroll_monthly FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS platform_fee_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "channel" TEXT,
  "fee_type" TEXT,
  "fee_name" TEXT,
  "rate" NUMERIC,
  "fixed_amount" NUMERIC,
  "effective_from" TEXT,
  "effective_to" TEXT,
  "memo" TEXT,
  "created_at" TIMESTAMPTZ,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_platform_fee_config_biz ON platform_fee_config(biz_id);
ALTER TABLE platform_fee_config ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON platform_fee_config;
CREATE POLICY service_role_all ON platform_fee_config FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON platform_fee_config;
CREATE POLICY tenant_isolation ON platform_fee_config FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS production_plan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "plan_date" TEXT,
  "product_name" TEXT,
  "current_stock" NUMERIC,
  "avg_daily_sales" NUMERIC,
  "depletion_days" NUMERIC,
  "safety_stock" NUMERIC,
  "lead_time_days" NUMERIC,
  "target_stock" NUMERIC,
  "recommended_production" NUMERIC,
  "status" TEXT,
  "unit" TEXT,
  "created_at" TIMESTAMPTZ,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_production_plan_biz ON production_plan(biz_id);
ALTER TABLE production_plan ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON production_plan;
CREATE POLICY service_role_all ON production_plan FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON production_plan;
CREATE POLICY tenant_isolation ON production_plan FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_name" TEXT,
  "barcode" TEXT,
  "sku" TEXT,
  "material_type" TEXT,
  "food_type" TEXT,
  "storage_method" TEXT,
  "cost_price" NUMERIC,
  "cost_type" TEXT,
  "naver_price" NUMERIC,
  "coupang_price" NUMERIC,
  "rocket_price" NUMERIC,
  "self_mall_price" NUMERIC,
  "unit" TEXT,
  "weight" NUMERIC,
  "weight_unit" TEXT,
  "purchase_unit" TEXT,
  "standard_unit" TEXT,
  "conversion_ratio" NUMERIC,
  "safety_stock" NUMERIC,
  "lead_time_days" NUMERIC,
  "is_active" BOOLEAN,
  "memo" TEXT,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  "name_normalized" TEXT,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_products_biz ON products(biz_id);
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON products;
CREATE POLICY service_role_all ON products FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON products;
CREATE POLICY tenant_isolation ON products FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS role_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" TEXT,
  "page_key" TEXT,
  "is_allowed" BOOLEAN,
  "updated_at" TIMESTAMPTZ,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_role_permissions_biz ON role_permissions(biz_id);
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON role_permissions;
CREATE POLICY service_role_all ON role_permissions FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON role_permissions;
CREATE POLICY tenant_isolation ON role_permissions FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS salary_components (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" BIGINT,
  "component_type" TEXT,
  "component_name" TEXT,
  "amount" NUMERIC,
  "is_taxable" BOOLEAN,
  "is_fixed" BOOLEAN,
  "effective_from" TEXT,
  "effective_to" TEXT,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  "biz_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_salary_components_biz ON salary_components(biz_id);
ALTER TABLE salary_components ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON salary_components;
CREATE POLICY service_role_all ON salary_components FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON salary_components;
CREATE POLICY tenant_isolation ON salary_components FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS promotions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "biz_id" BIGINT NOT NULL,
  "name" TEXT,
  "product_name" TEXT,
  "category" TEXT,
  "start_date" TEXT,
  "end_date" TEXT,
  "promo_price" NUMERIC,
  "discount_type" TEXT,
  "discount_value" NUMERIC,
  "is_active" BOOLEAN,
  "is_deleted" BOOLEAN,
  "created_at" TIMESTAMPTZ,
  "memo" TEXT,
  "created_by" TEXT
);
CREATE INDEX IF NOT EXISTS idx_promotions_biz ON promotions(biz_id);
ALTER TABLE promotions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON promotions;
CREATE POLICY service_role_all ON promotions FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON promotions;
CREATE POLICY tenant_isolation ON promotions FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "biz_id" BIGINT NOT NULL,
  "name" TEXT,
  "channel" TEXT,
  "discount_type" TEXT,
  "discount_value" NUMERIC,
  "start_date" TEXT,
  "end_date" TEXT,
  "is_active" BOOLEAN,
  "is_deleted" BOOLEAN,
  "created_at" TIMESTAMPTZ,
  "product_name" TEXT,
  "category" TEXT,
  "memo" TEXT,
  "created_by" TEXT
);
CREATE INDEX IF NOT EXISTS idx_coupons_biz ON coupons(biz_id);
ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON coupons;
CREATE POLICY service_role_all ON coupons FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON coupons;
CREATE POLICY tenant_isolation ON coupons FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS product_cost_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "biz_id" BIGINT NOT NULL,
  "product_name" TEXT,
  "old_cost_price" NUMERIC,
  "new_cost_price" NUMERIC,
  "old_conversion_ratio" NUMERIC,
  "new_conversion_ratio" NUMERIC,
  "changed_by" TEXT,
  "change_reason" TEXT,
  "effective_date" TEXT,
  "created_at" TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_product_cost_history_biz ON product_cost_history(biz_id);
ALTER TABLE product_cost_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON product_cost_history;
CREATE POLICY service_role_all ON product_cost_history FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON product_cost_history;
CREATE POLICY tenant_isolation ON product_cost_history FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS employee_insurance_overrides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "biz_id" BIGINT NOT NULL,
  "employee_id" BIGINT,
  "insurance_type" TEXT,
  "rate" NUMERIC,
  "amount" NUMERIC,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_employee_insurance_overrides_biz ON employee_insurance_overrides(biz_id);
ALTER TABLE employee_insurance_overrides ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON employee_insurance_overrides;
CREATE POLICY service_role_all ON employee_insurance_overrides FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON employee_insurance_overrides;
CREATE POLICY tenant_isolation ON employee_insurance_overrides FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS platform_settlements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "biz_id" BIGINT NOT NULL,
  "channel" TEXT,
  "settlement_date" TEXT,
  "order_no" TEXT,
  "amount" NUMERIC,
  "fee" NUMERIC,
  "raw_data" JSONB,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_platform_settlements_biz ON platform_settlements(biz_id);
ALTER TABLE platform_settlements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON platform_settlements;
CREATE POLICY service_role_all ON platform_settlements FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON platform_settlements;
CREATE POLICY tenant_isolation ON platform_settlements FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);

CREATE TABLE IF NOT EXISTS bom (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "biz_id" BIGINT NOT NULL,
  "product_name" TEXT,
  "component_name" TEXT,
  "qty" NUMERIC,
  "unit" TEXT,
  "is_deleted" BOOLEAN,
  "created_at" TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_bom_biz ON bom(biz_id);
ALTER TABLE bom ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all ON bom;
CREATE POLICY service_role_all ON bom FOR ALL TO service_role USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS tenant_isolation ON bom;
CREATE POLICY tenant_isolation ON bom FOR ALL TO authenticated
  USING (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint)
  WITH CHECK (biz_id=(NULLIF(current_setting('app.current_biz_id',true),''))::bigint);
